---
{{- $component := "db" -}}
{{- $image := .Values.db.image -}}
{{- $autoscaling := .Values.db.autoscaling -}}
{{- $replicaCount := .Values.db.replicaCount -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rmt.fullname" . }}-{{ $component }}
  labels:
    {{- include "rmt.labels" . | nindent 4 }}
    component: {{ $component }}
spec:
  {{- if not $autoscaling.enabled }}
  replicas: {{ $replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rmt.selectorLabels" . | nindent 6 }}
      component: {{ $component }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rmt.selectorLabels" . | nindent 8 }}
        component: {{ $component }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rmt.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: "{{ .Chart.Name }}-{{ $component }}"
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ $image.repository }}:{{ $image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ $image.pullPolicy | default "IfNotPresent" }}
        ports:
          - name: {{ $component }}
            containerPort: 3306
            protocol: TCP
        env:
        - name: MYSQL_DATABASE
          value: {{ .Values.db.mysql.database }}
        - name: MYSQL_USER
          value: {{ .Values.db.mysql.user }}
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "rmt.fullname" . }}-{{ $component }}
              key: password
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ include "rmt.fullname" . }}-{{ $component }}
              key: rootPassword
        volumeMounts:
        - name: {{ include "rmt.fullname" . }}-{{ $component }}
          mountPath: /var/lib/mysql
      volumes:
      - name: {{ include "rmt.fullname" . }}-{{ $component }}
        persistentVolumeClaim:
          claimName: {{ include "rmt.fullname" . }}-{{ $component }}