---
{{- $component := "app" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rmt.fullname" . }}-{{ $component }}
type: Opaque
data:
  username: {{ required "SCC username is required" .Values.app.scc.username | b64enc | quote }}
  password: {{ required "SCC password is required" .Values.app.scc.password | b64enc | quote }}