---
{{- $component := "db" -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rmt.fullname" . }}-{{ $component }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.db.storage.class }}
  resources:
    requests:
      storage: {{ .Values.db.storage.size }}
