---
{{- $component := "db" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rmt.fullname" . }}-{{ $component }}
type: Opaque
data:
  {{- if .Release.IsInstall }}
  password: {{ .Values.db.mysql.password | default (randAlphaNum 10) | b64enc | quote }}
  {{- else }}
  password: {{ (lookup "v1" "Secret" .Release.Namespace (printf "%s-db" .Release.Name)).data.password }}
  {{- end }}
  {{- if .Release.IsInstall }}
  rootPassword: {{ .Values.db.mysql.rootPassword | default (randAlphaNum 10) | b64enc | quote }}
  {{- else }}
  rootPassword: {{ (lookup "v1" "Secret" .Release.Namespace (printf "%s-db" .Release.Name)).data.rootPassword }}
  {{- end }}