apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.db.storage.class }}
  resources:
    requests:
      storage: {{ .Values.db.storage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.app.storage.class }}
  resources:
    requests:
      storage: {{ .Values.app.storage.size }}
