apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-db-svc"
  labels:
    app: mariadb
spec:
  ports:
    - port: 3306
  selector:
    app: mariadb
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-app-svc"
  labels:
    app: rmt-server
spec:
  ports:
    - protocol: TCP
      port: {{ .Values.app.service.port }}
      targetPort: suseconnect
  selector:
    app: rmt-server